<a href="https://colab.research.google.com/github/it221291/Python/blob/main/PP_LAB_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1. i) Write a program to convert a list and tuple into arrays.
import numpy as np
my_list = [1,2,3,4,5,6,7,8,9]
print("list to array :") 
print(np.asarray(my_list))
my_tuple = ([8,4,6],[1,2,3])
print("tuple to array :")
print(np.asarray(my_tuple))

list to array :
[1 2 3 4 5 6 7 8 9]
tuple to array :
[[8 4 6]
 [1 2 3]]


In [3]:
#ii) Write a program to find common values between two arrays.
import numpy as np 
array1 =np.array([0,10,20,40,60])
print("Array 1:" ,array1)
array2= [10,30,40]
print("Array 2:",array2)
print("common values between two arrays:")
print(np.intersect1d(array1,array2))


Array 1: [ 0 10 20 40 60]
Array 2: [10, 30, 40]
common values between two arrays:
[10 40]


In [6]:
# 2. Write a function called gcd that takes parameters a and b and returns their greatest common divisor.
def GCD(x,y):
  while(y):
    x,y=y,x%y
  return abs(x)
print("the gcd of 60 and 120 is:")
print(GCD(60,120))

the gcd of 60 and 120 is:
60


In [7]:
#3. Write a function called palindrome that takes a string argument and returns True if it is a palindrome and False otherwise. Remember that you can use the built-in function len to check the length of a string 
def isPalindrome(s):
    return s == s[::-1]
  
  
# Driver code
s = "malayalam"
ans = isPalindrome(s)
  
if ans:
    print("Yes")
else:
    print("No")

Yes
